package cafe.woden.ircclient.ui.settings;

import cafe.woden.ircclient.config.api.NotificationRule;
import cafe.woden.ircclient.ui.settings.memory.MemoryUsageDisplayMode;
import java.util.List;

public record UiSettings(
    String theme,
    String chatFontFamily,
    int chatFontSize,
    boolean autoConnectOnStart,
    boolean trayEnabled,
    boolean trayCloseToTray,
    boolean trayMinimizeToTray,
    boolean trayStartMinimized,
    boolean trayNotifyHighlights,
    boolean trayNotifyPrivateMessages,
    boolean trayNotifyConnectionState,
    boolean trayNotifyOnlyWhenUnfocused,
    boolean trayNotifyOnlyWhenMinimizedOrHidden,
    boolean trayNotifySuppressWhenTargetActive,
    boolean trayLinuxDbusActionsEnabled,
    NotificationBackendMode trayNotificationBackendMode,
    boolean imageEmbedsEnabled,
    boolean imageEmbedsCollapsedByDefault,
    int imageEmbedsMaxWidthPx,
    int imageEmbedsMaxHeightPx,
    boolean imageEmbedsAnimateGifs,
    boolean linkPreviewsEnabled,
    boolean linkPreviewsCollapsedByDefault,
    boolean presenceFoldsEnabled,
    boolean ctcpRequestsInActiveTargetEnabled,
    boolean typingIndicatorsEnabled,
    boolean typingIndicatorsReceiveEnabled,
    String typingIndicatorsTreeStyle,
    boolean typingIndicatorsTreeEnabled,
    boolean typingIndicatorsUsersListEnabled,
    boolean typingIndicatorsTranscriptEnabled,
    boolean typingIndicatorsSendSignalEnabled,
    boolean timestampsEnabled,
    String timestampFormat,
    boolean timestampsIncludeChatMessages,
    boolean timestampsIncludePresenceMessages,
    int chatHistoryInitialLoadLines,
    int chatHistoryPageSize,
    int chatHistoryAutoLoadWheelDebounceMs,
    int chatHistoryLoadOlderChunkSize,
    int chatHistoryLoadOlderChunkDelayMs,
    int chatHistoryLoadOlderChunkEdtBudgetMs,
    boolean chatHistoryDeferRichTextDuringBatch,
    int chatHistoryRemoteRequestTimeoutSeconds,
    int chatHistoryRemoteZncPlaybackTimeoutSeconds,
    int chatHistoryRemoteZncPlaybackWindowMinutes,
    int commandHistoryMaxSize,
    int chatTranscriptMaxLinesPerTarget,
    boolean clientLineColorEnabled,
    String clientLineColor,
    boolean outgoingDeliveryIndicatorsEnabled,
    boolean serverTreeNotificationBadgesEnabled,

    // --- Hostmask discovery / USERHOST anti-flood ---

    boolean userhostDiscoveryEnabled,
    int userhostMinIntervalSeconds,
    int userhostMaxCommandsPerMinute,
    int userhostNickCooldownMinutes,
    int userhostMaxNicksPerCommand,

    // --- General user info enrichment (fallback) ---

    boolean userInfoEnrichmentEnabled,
    int userInfoEnrichmentUserhostMinIntervalSeconds,
    int userInfoEnrichmentUserhostMaxCommandsPerMinute,
    int userInfoEnrichmentUserhostNickCooldownMinutes,
    int userInfoEnrichmentUserhostMaxNicksPerCommand,
    boolean userInfoEnrichmentWhoisFallbackEnabled,
    int userInfoEnrichmentWhoisMinIntervalSeconds,
    int userInfoEnrichmentWhoisNickCooldownMinutes,
    boolean userInfoEnrichmentPeriodicRefreshEnabled,
    int userInfoEnrichmentPeriodicRefreshIntervalSeconds,
    int userInfoEnrichmentPeriodicRefreshNicksPerTick,
    int monitorIsonFallbackPollIntervalSeconds,
    int notificationRuleCooldownSeconds,
    MemoryUsageDisplayMode memoryUsageDisplayMode,
    int memoryUsageRefreshIntervalMs,
    int memoryUsageWarningNearMaxPercent,
    boolean memoryUsageWarningTooltipEnabled,
    boolean memoryUsageWarningToastEnabled,
    boolean memoryUsageWarningPushyEnabled,
    boolean memoryUsageWarningSoundEnabled,
    List<NotificationRule> notificationRules,
    String serverTreeUnreadChannelColor,
    String serverTreeHighlightChannelColor,
    boolean preserveDockLayoutBetweenSessions,
    String matrixUserListNameDisplayMode) {

  public UiSettings {
    // Preferred default theme (A): Darcula.
    if (theme == null || theme.isBlank()) theme = "darcula";
    if (chatFontFamily == null || chatFontFamily.isBlank()) chatFontFamily = "Monospaced";
    if (chatFontSize <= 0) chatFontSize = 12;

    // Tray settings: if the tray is disabled, ensure tray behaviors are off too.
    if (!trayEnabled) {
      trayCloseToTray = false;
      trayMinimizeToTray = false;
      trayStartMinimized = false;

      trayNotifyHighlights = false;
      trayNotifyPrivateMessages = false;
      trayNotifyConnectionState = false;

      trayNotifyOnlyWhenUnfocused = false;
      trayNotifyOnlyWhenMinimizedOrHidden = false;
      trayNotifySuppressWhenTargetActive = false;

      trayLinuxDbusActionsEnabled = false;
    }
    if (trayNotificationBackendMode == null)
      trayNotificationBackendMode = NotificationBackendMode.AUTO;

    imageEmbedsMaxWidthPx =
        SettingsRangeSupport.normalizeImageEmbedDimensionPx(imageEmbedsMaxWidthPx);
    imageEmbedsMaxHeightPx =
        SettingsRangeSupport.normalizeImageEmbedDimensionPx(imageEmbedsMaxHeightPx);

    if (timestampFormat == null || timestampFormat.isBlank()) timestampFormat = "HH:mm:ss";
    typingIndicatorsTreeStyle = normalizeTypingTreeIndicatorStyle(typingIndicatorsTreeStyle);
    matrixUserListNameDisplayMode =
        normalizeMatrixUserListNameDisplayMode(matrixUserListNameDisplayMode);

    chatHistoryInitialLoadLines =
        SettingsRangeSupport.normalizeChatHistoryInitialLoadLines(chatHistoryInitialLoadLines);
    chatHistoryPageSize = SettingsRangeSupport.normalizeChatHistoryPageSize(chatHistoryPageSize);
    chatHistoryAutoLoadWheelDebounceMs =
        SettingsRangeSupport.normalizeChatHistoryAutoLoadWheelDebounceMs(
            chatHistoryAutoLoadWheelDebounceMs);
    chatHistoryLoadOlderChunkSize =
        SettingsRangeSupport.normalizeChatHistoryLoadOlderChunkSize(chatHistoryLoadOlderChunkSize);
    chatHistoryLoadOlderChunkDelayMs =
        SettingsRangeSupport.normalizeChatHistoryLoadOlderChunkDelayMs(
            chatHistoryLoadOlderChunkDelayMs);
    chatHistoryLoadOlderChunkEdtBudgetMs =
        SettingsRangeSupport.normalizeChatHistoryLoadOlderChunkEdtBudgetMs(
            chatHistoryLoadOlderChunkEdtBudgetMs);
    chatHistoryRemoteRequestTimeoutSeconds =
        SettingsRangeSupport.normalizeChatHistoryRemoteRequestTimeoutSeconds(
            chatHistoryRemoteRequestTimeoutSeconds);
    chatHistoryRemoteZncPlaybackTimeoutSeconds =
        SettingsRangeSupport.normalizeChatHistoryRemoteZncPlaybackTimeoutSeconds(
            chatHistoryRemoteZncPlaybackTimeoutSeconds);
    chatHistoryRemoteZncPlaybackWindowMinutes =
        SettingsRangeSupport.normalizeChatHistoryRemoteZncPlaybackWindowMinutes(
            chatHistoryRemoteZncPlaybackWindowMinutes);
    commandHistoryMaxSize =
        SettingsRangeSupport.normalizeCommandHistoryMaxSize(commandHistoryMaxSize);
    chatTranscriptMaxLinesPerTarget =
        SettingsRangeSupport.normalizeChatTranscriptMaxLinesPerTarget(
            chatTranscriptMaxLinesPerTarget);

    clientLineColor = normalizeHexOrDefault(clientLineColor, "#6AA2FF");

    // Hostmask discovery / USERHOST anti-flood
    userhostMinIntervalSeconds =
        SettingsRangeSupport.normalizeUserhostMinIntervalSeconds(userhostMinIntervalSeconds);
    userhostMaxCommandsPerMinute =
        SettingsRangeSupport.normalizeUserhostMaxCommandsPerMinute(userhostMaxCommandsPerMinute);
    userhostNickCooldownMinutes =
        SettingsRangeSupport.normalizeUserhostNickCooldownMinutes(userhostNickCooldownMinutes);
    userhostMaxNicksPerCommand =
        SettingsRangeSupport.normalizeUserhostMaxNicksPerCommand(userhostMaxNicksPerCommand);

    // General user info enrichment (fallback)
    userInfoEnrichmentUserhostMinIntervalSeconds =
        SettingsRangeSupport.normalizeEnrichmentUserhostMinIntervalSeconds(
            userInfoEnrichmentUserhostMinIntervalSeconds);
    userInfoEnrichmentUserhostMaxCommandsPerMinute =
        SettingsRangeSupport.normalizeEnrichmentUserhostMaxCommandsPerMinute(
            userInfoEnrichmentUserhostMaxCommandsPerMinute);
    userInfoEnrichmentUserhostNickCooldownMinutes =
        SettingsRangeSupport.normalizeEnrichmentUserhostNickCooldownMinutes(
            userInfoEnrichmentUserhostNickCooldownMinutes);
    userInfoEnrichmentUserhostMaxNicksPerCommand =
        SettingsRangeSupport.normalizeUserhostMaxNicksPerCommand(
            userInfoEnrichmentUserhostMaxNicksPerCommand);
    userInfoEnrichmentWhoisMinIntervalSeconds =
        SettingsRangeSupport.normalizeEnrichmentWhoisMinIntervalSeconds(
            userInfoEnrichmentWhoisMinIntervalSeconds);
    userInfoEnrichmentWhoisNickCooldownMinutes =
        SettingsRangeSupport.normalizeEnrichmentWhoisNickCooldownMinutes(
            userInfoEnrichmentWhoisNickCooldownMinutes);
    userInfoEnrichmentPeriodicRefreshIntervalSeconds =
        SettingsRangeSupport.normalizeEnrichmentPeriodicRefreshIntervalSeconds(
            userInfoEnrichmentPeriodicRefreshIntervalSeconds);
    userInfoEnrichmentPeriodicRefreshNicksPerTick =
        SettingsRangeSupport.normalizeEnrichmentPeriodicRefreshNicksPerTick(
            userInfoEnrichmentPeriodicRefreshNicksPerTick);
    monitorIsonFallbackPollIntervalSeconds =
        SettingsRangeSupport.normalizeMonitorIsonFallbackPollIntervalSeconds(
            monitorIsonFallbackPollIntervalSeconds);
    notificationRuleCooldownSeconds =
        SettingsRangeSupport.normalizeNotificationRuleCooldownSeconds(
            notificationRuleCooldownSeconds);

    if (memoryUsageDisplayMode == null) memoryUsageDisplayMode = MemoryUsageDisplayMode.LONG;
    memoryUsageRefreshIntervalMs =
        SettingsRangeSupport.normalizeMemoryUsageRefreshIntervalMs(memoryUsageRefreshIntervalMs);
    memoryUsageWarningNearMaxPercent =
        SettingsRangeSupport.normalizeMemoryUsageWarningNearMaxPercent(
            memoryUsageWarningNearMaxPercent);

    if (notificationRules == null) notificationRules = List.of();
    serverTreeUnreadChannelColor = normalizeHexOrNull(serverTreeUnreadChannelColor);
    serverTreeHighlightChannelColor = normalizeHexOrNull(serverTreeHighlightChannelColor);
  }

  /**
   * Back-compat constructor to keep older call sites compiling.
   *
   * <p>Newer user info enrichment fields are defaulted to conservative values and disabled by
   * default.
   */
  public UiSettings(
      String theme,
      String chatFontFamily,
      int chatFontSize,
      boolean autoConnectOnStart,
      boolean imageEmbedsEnabled,
      boolean imageEmbedsCollapsedByDefault,
      int imageEmbedsMaxWidthPx,
      int imageEmbedsMaxHeightPx,
      boolean imageEmbedsAnimateGifs,
      boolean linkPreviewsEnabled,
      boolean linkPreviewsCollapsedByDefault,
      boolean presenceFoldsEnabled,
      boolean ctcpRequestsInActiveTargetEnabled,
      boolean timestampsEnabled,
      String timestampFormat,
      boolean timestampsIncludeChatMessages,
      int chatHistoryInitialLoadLines,
      int chatHistoryPageSize,
      boolean clientLineColorEnabled,
      String clientLineColor,
      boolean userhostDiscoveryEnabled,
      int userhostMinIntervalSeconds,
      int userhostMaxCommandsPerMinute,
      int userhostNickCooldownMinutes,
      int userhostMaxNicksPerCommand) {
    this(
        theme,
        chatFontFamily,
        chatFontSize,
        autoConnectOnStart,
        // Tray defaults (older call sites)
        true,
        true,
        false,
        false,
        true,
        true,
        false,
        true,
        false,
        true,
        true,
        NotificationBackendMode.AUTO,
        imageEmbedsEnabled,
        imageEmbedsCollapsedByDefault,
        imageEmbedsMaxWidthPx,
        imageEmbedsMaxHeightPx,
        imageEmbedsAnimateGifs,
        linkPreviewsEnabled,
        linkPreviewsCollapsedByDefault,
        presenceFoldsEnabled,
        ctcpRequestsInActiveTargetEnabled,
        true,
        true,
        "dots",
        true,
        true,
        true,
        true,
        timestampsEnabled,
        timestampFormat,
        timestampsIncludeChatMessages,
        true,
        chatHistoryInitialLoadLines,
        chatHistoryPageSize,
        2000,
        20,
        0,
        6,
        false,
        6,
        18,
        360,
        500,
        4000,
        clientLineColorEnabled,
        clientLineColor,
        true,
        true,
        userhostDiscoveryEnabled,
        userhostMinIntervalSeconds,
        userhostMaxCommandsPerMinute,
        userhostNickCooldownMinutes,
        userhostMaxNicksPerCommand,

        // New fields
        false,
        15,
        3,
        60,
        5,
        false,
        45,
        120,
        false,
        300,
        2,
        30,
        15,
        MemoryUsageDisplayMode.LONG,
        1000,
        5,
        true,
        false,
        false,
        false,
        List.of(),
        null,
        null,
        false,
        "compact");
  }

  public static String normalizeHexOrDefault(String raw, String fallback) {
    String fb = SettingsColorSupport.normalizeHexColor(fallback);
    if (fb == null) fb = "#6AA2FF";
    String normalized = SettingsColorSupport.normalizeHexColor(raw);
    return normalized != null ? normalized : fb;
  }

  static String normalizeHexOrNull(String raw) {
    return SettingsColorSupport.normalizeHexColor(raw);
  }

  public static String normalizeTypingTreeIndicatorStyle(String raw) {
    String s = SettingsValueSupport.lowerTrimmedString(raw);
    if (s.isEmpty()) return "dots";
    return switch (s) {
      case "dots", "ellipsis" -> "dots";
      case "keyboard", "kbd" -> "keyboard";
      case "glow-dot", "glowdot", "dot", "green-dot", "glowing-green-dot" -> "glow-dot";
      default -> "dots";
    };
  }

  public static String normalizeMatrixUserListNameDisplayMode(String raw) {
    String s = SettingsValueSupport.lowerTrimmedString(raw);
    if (s.isEmpty()) return "compact";
    return switch (s) {
      case "compact", "display-name-only", "displayname", "name-only" -> "compact";
      case "verbose", "display-name-and-user-id", "displayname-and-userid", "full" -> "verbose";
      default -> "compact";
    };
  }

  public UiSettings withTheme(String nextTheme) {
    return new UiSettings(
        nextTheme,
        chatFontFamily,
        chatFontSize,
        autoConnectOnStart,
        trayEnabled,
        trayCloseToTray,
        trayMinimizeToTray,
        trayStartMinimized,
        trayNotifyHighlights,
        trayNotifyPrivateMessages,
        trayNotifyConnectionState,
        trayNotifyOnlyWhenUnfocused,
        trayNotifyOnlyWhenMinimizedOrHidden,
        trayNotifySuppressWhenTargetActive,
        trayLinuxDbusActionsEnabled,
        trayNotificationBackendMode,
        imageEmbedsEnabled,
        imageEmbedsCollapsedByDefault,
        imageEmbedsMaxWidthPx,
        imageEmbedsMaxHeightPx,
        imageEmbedsAnimateGifs,
        linkPreviewsEnabled,
        linkPreviewsCollapsedByDefault,
        presenceFoldsEnabled,
        ctcpRequestsInActiveTargetEnabled,
        typingIndicatorsEnabled,
        typingIndicatorsReceiveEnabled,
        typingIndicatorsTreeStyle,
        typingIndicatorsTreeEnabled,
        typingIndicatorsUsersListEnabled,
        typingIndicatorsTranscriptEnabled,
        typingIndicatorsSendSignalEnabled,
        timestampsEnabled,
        timestampFormat,
        timestampsIncludeChatMessages,
        timestampsIncludePresenceMessages,
        chatHistoryInitialLoadLines,
        chatHistoryPageSize,
        chatHistoryAutoLoadWheelDebounceMs,
        chatHistoryLoadOlderChunkSize,
        chatHistoryLoadOlderChunkDelayMs,
        chatHistoryLoadOlderChunkEdtBudgetMs,
        chatHistoryDeferRichTextDuringBatch,
        chatHistoryRemoteRequestTimeoutSeconds,
        chatHistoryRemoteZncPlaybackTimeoutSeconds,
        chatHistoryRemoteZncPlaybackWindowMinutes,
        commandHistoryMaxSize,
        chatTranscriptMaxLinesPerTarget,
        clientLineColorEnabled,
        clientLineColor,
        outgoingDeliveryIndicatorsEnabled,
        serverTreeNotificationBadgesEnabled,
        userhostDiscoveryEnabled,
        userhostMinIntervalSeconds,
        userhostMaxCommandsPerMinute,
        userhostNickCooldownMinutes,
        userhostMaxNicksPerCommand,
        userInfoEnrichmentEnabled,
        userInfoEnrichmentUserhostMinIntervalSeconds,
        userInfoEnrichmentUserhostMaxCommandsPerMinute,
        userInfoEnrichmentUserhostNickCooldownMinutes,
        userInfoEnrichmentUserhostMaxNicksPerCommand,
        userInfoEnrichmentWhoisFallbackEnabled,
        userInfoEnrichmentWhoisMinIntervalSeconds,
        userInfoEnrichmentWhoisNickCooldownMinutes,
        userInfoEnrichmentPeriodicRefreshEnabled,
        userInfoEnrichmentPeriodicRefreshIntervalSeconds,
        userInfoEnrichmentPeriodicRefreshNicksPerTick,
        monitorIsonFallbackPollIntervalSeconds,
        notificationRuleCooldownSeconds,
        memoryUsageDisplayMode,
        memoryUsageRefreshIntervalMs,
        memoryUsageWarningNearMaxPercent,
        memoryUsageWarningTooltipEnabled,
        memoryUsageWarningToastEnabled,
        memoryUsageWarningPushyEnabled,
        memoryUsageWarningSoundEnabled,
        notificationRules,
        serverTreeUnreadChannelColor,
        serverTreeHighlightChannelColor,
        preserveDockLayoutBetweenSessions,
        matrixUserListNameDisplayMode);
  }

  public UiSettings withChatFontFamily(String family) {
    return new UiSettings(
        theme,
        family,
        chatFontSize,
        autoConnectOnStart,
        trayEnabled,
        trayCloseToTray,
        trayMinimizeToTray,
        trayStartMinimized,
        trayNotifyHighlights,
        trayNotifyPrivateMessages,
        trayNotifyConnectionState,
        trayNotifyOnlyWhenUnfocused,
        trayNotifyOnlyWhenMinimizedOrHidden,
        trayNotifySuppressWhenTargetActive,
        trayLinuxDbusActionsEnabled,
        trayNotificationBackendMode,
        imageEmbedsEnabled,
        imageEmbedsCollapsedByDefault,
        imageEmbedsMaxWidthPx,
        imageEmbedsMaxHeightPx,
        imageEmbedsAnimateGifs,
        linkPreviewsEnabled,
        linkPreviewsCollapsedByDefault,
        presenceFoldsEnabled,
        ctcpRequestsInActiveTargetEnabled,
        typingIndicatorsEnabled,
        typingIndicatorsReceiveEnabled,
        typingIndicatorsTreeStyle,
        typingIndicatorsTreeEnabled,
        typingIndicatorsUsersListEnabled,
        typingIndicatorsTranscriptEnabled,
        typingIndicatorsSendSignalEnabled,
        timestampsEnabled,
        timestampFormat,
        timestampsIncludeChatMessages,
        timestampsIncludePresenceMessages,
        chatHistoryInitialLoadLines,
        chatHistoryPageSize,
        chatHistoryAutoLoadWheelDebounceMs,
        chatHistoryLoadOlderChunkSize,
        chatHistoryLoadOlderChunkDelayMs,
        chatHistoryLoadOlderChunkEdtBudgetMs,
        chatHistoryDeferRichTextDuringBatch,
        chatHistoryRemoteRequestTimeoutSeconds,
        chatHistoryRemoteZncPlaybackTimeoutSeconds,
        chatHistoryRemoteZncPlaybackWindowMinutes,
        commandHistoryMaxSize,
        chatTranscriptMaxLinesPerTarget,
        clientLineColorEnabled,
        clientLineColor,
        outgoingDeliveryIndicatorsEnabled,
        serverTreeNotificationBadgesEnabled,
        userhostDiscoveryEnabled,
        userhostMinIntervalSeconds,
        userhostMaxCommandsPerMinute,
        userhostNickCooldownMinutes,
        userhostMaxNicksPerCommand,
        userInfoEnrichmentEnabled,
        userInfoEnrichmentUserhostMinIntervalSeconds,
        userInfoEnrichmentUserhostMaxCommandsPerMinute,
        userInfoEnrichmentUserhostNickCooldownMinutes,
        userInfoEnrichmentUserhostMaxNicksPerCommand,
        userInfoEnrichmentWhoisFallbackEnabled,
        userInfoEnrichmentWhoisMinIntervalSeconds,
        userInfoEnrichmentWhoisNickCooldownMinutes,
        userInfoEnrichmentPeriodicRefreshEnabled,
        userInfoEnrichmentPeriodicRefreshIntervalSeconds,
        userInfoEnrichmentPeriodicRefreshNicksPerTick,
        monitorIsonFallbackPollIntervalSeconds,
        notificationRuleCooldownSeconds,
        memoryUsageDisplayMode,
        memoryUsageRefreshIntervalMs,
        memoryUsageWarningNearMaxPercent,
        memoryUsageWarningTooltipEnabled,
        memoryUsageWarningToastEnabled,
        memoryUsageWarningPushyEnabled,
        memoryUsageWarningSoundEnabled,
        notificationRules,
        serverTreeUnreadChannelColor,
        serverTreeHighlightChannelColor,
        preserveDockLayoutBetweenSessions,
        matrixUserListNameDisplayMode);
  }

  public UiSettings withChatFontSize(int size) {
    return new UiSettings(
        theme,
        chatFontFamily,
        size,
        autoConnectOnStart,
        trayEnabled,
        trayCloseToTray,
        trayMinimizeToTray,
        trayStartMinimized,
        trayNotifyHighlights,
        trayNotifyPrivateMessages,
        trayNotifyConnectionState,
        trayNotifyOnlyWhenUnfocused,
        trayNotifyOnlyWhenMinimizedOrHidden,
        trayNotifySuppressWhenTargetActive,
        trayLinuxDbusActionsEnabled,
        trayNotificationBackendMode,
        imageEmbedsEnabled,
        imageEmbedsCollapsedByDefault,
        imageEmbedsMaxWidthPx,
        imageEmbedsMaxHeightPx,
        imageEmbedsAnimateGifs,
        linkPreviewsEnabled,
        linkPreviewsCollapsedByDefault,
        presenceFoldsEnabled,
        ctcpRequestsInActiveTargetEnabled,
        typingIndicatorsEnabled,
        typingIndicatorsReceiveEnabled,
        typingIndicatorsTreeStyle,
        typingIndicatorsTreeEnabled,
        typingIndicatorsUsersListEnabled,
        typingIndicatorsTranscriptEnabled,
        typingIndicatorsSendSignalEnabled,
        timestampsEnabled,
        timestampFormat,
        timestampsIncludeChatMessages,
        timestampsIncludePresenceMessages,
        chatHistoryInitialLoadLines,
        chatHistoryPageSize,
        chatHistoryAutoLoadWheelDebounceMs,
        chatHistoryLoadOlderChunkSize,
        chatHistoryLoadOlderChunkDelayMs,
        chatHistoryLoadOlderChunkEdtBudgetMs,
        chatHistoryDeferRichTextDuringBatch,
        chatHistoryRemoteRequestTimeoutSeconds,
        chatHistoryRemoteZncPlaybackTimeoutSeconds,
        chatHistoryRemoteZncPlaybackWindowMinutes,
        commandHistoryMaxSize,
        chatTranscriptMaxLinesPerTarget,
        clientLineColorEnabled,
        clientLineColor,
        outgoingDeliveryIndicatorsEnabled,
        serverTreeNotificationBadgesEnabled,
        userhostDiscoveryEnabled,
        userhostMinIntervalSeconds,
        userhostMaxCommandsPerMinute,
        userhostNickCooldownMinutes,
        userhostMaxNicksPerCommand,
        userInfoEnrichmentEnabled,
        userInfoEnrichmentUserhostMinIntervalSeconds,
        userInfoEnrichmentUserhostMaxCommandsPerMinute,
        userInfoEnrichmentUserhostNickCooldownMinutes,
        userInfoEnrichmentUserhostMaxNicksPerCommand,
        userInfoEnrichmentWhoisFallbackEnabled,
        userInfoEnrichmentWhoisMinIntervalSeconds,
        userInfoEnrichmentWhoisNickCooldownMinutes,
        userInfoEnrichmentPeriodicRefreshEnabled,
        userInfoEnrichmentPeriodicRefreshIntervalSeconds,
        userInfoEnrichmentPeriodicRefreshNicksPerTick,
        monitorIsonFallbackPollIntervalSeconds,
        notificationRuleCooldownSeconds,
        memoryUsageDisplayMode,
        memoryUsageRefreshIntervalMs,
        memoryUsageWarningNearMaxPercent,
        memoryUsageWarningTooltipEnabled,
        memoryUsageWarningToastEnabled,
        memoryUsageWarningPushyEnabled,
        memoryUsageWarningSoundEnabled,
        notificationRules,
        serverTreeUnreadChannelColor,
        serverTreeHighlightChannelColor,
        preserveDockLayoutBetweenSessions,
        matrixUserListNameDisplayMode);
  }

  public UiSettings withImageEmbedsEnabled(boolean enabled) {
    return new UiSettings(
        theme,
        chatFontFamily,
        chatFontSize,
        autoConnectOnStart,
        trayEnabled,
        trayCloseToTray,
        trayMinimizeToTray,
        trayStartMinimized,
        trayNotifyHighlights,
        trayNotifyPrivateMessages,
        trayNotifyConnectionState,
        trayNotifyOnlyWhenUnfocused,
        trayNotifyOnlyWhenMinimizedOrHidden,
        trayNotifySuppressWhenTargetActive,
        trayLinuxDbusActionsEnabled,
        trayNotificationBackendMode,
        enabled,
        imageEmbedsCollapsedByDefault,
        imageEmbedsMaxWidthPx,
        imageEmbedsMaxHeightPx,
        imageEmbedsAnimateGifs,
        linkPreviewsEnabled,
        linkPreviewsCollapsedByDefault,
        presenceFoldsEnabled,
        ctcpRequestsInActiveTargetEnabled,
        typingIndicatorsEnabled,
        typingIndicatorsReceiveEnabled,
        typingIndicatorsTreeStyle,
        typingIndicatorsTreeEnabled,
        typingIndicatorsUsersListEnabled,
        typingIndicatorsTranscriptEnabled,
        typingIndicatorsSendSignalEnabled,
        timestampsEnabled,
        timestampFormat,
        timestampsIncludeChatMessages,
        timestampsIncludePresenceMessages,
        chatHistoryInitialLoadLines,
        chatHistoryPageSize,
        chatHistoryAutoLoadWheelDebounceMs,
        chatHistoryLoadOlderChunkSize,
        chatHistoryLoadOlderChunkDelayMs,
        chatHistoryLoadOlderChunkEdtBudgetMs,
        chatHistoryDeferRichTextDuringBatch,
        chatHistoryRemoteRequestTimeoutSeconds,
        chatHistoryRemoteZncPlaybackTimeoutSeconds,
        chatHistoryRemoteZncPlaybackWindowMinutes,
        commandHistoryMaxSize,
        chatTranscriptMaxLinesPerTarget,
        clientLineColorEnabled,
        clientLineColor,
        outgoingDeliveryIndicatorsEnabled,
        serverTreeNotificationBadgesEnabled,
        userhostDiscoveryEnabled,
        userhostMinIntervalSeconds,
        userhostMaxCommandsPerMinute,
        userhostNickCooldownMinutes,
        userhostMaxNicksPerCommand,
        userInfoEnrichmentEnabled,
        userInfoEnrichmentUserhostMinIntervalSeconds,
        userInfoEnrichmentUserhostMaxCommandsPerMinute,
        userInfoEnrichmentUserhostNickCooldownMinutes,
        userInfoEnrichmentUserhostMaxNicksPerCommand,
        userInfoEnrichmentWhoisFallbackEnabled,
        userInfoEnrichmentWhoisMinIntervalSeconds,
        userInfoEnrichmentWhoisNickCooldownMinutes,
        userInfoEnrichmentPeriodicRefreshEnabled,
        userInfoEnrichmentPeriodicRefreshIntervalSeconds,
        userInfoEnrichmentPeriodicRefreshNicksPerTick,
        monitorIsonFallbackPollIntervalSeconds,
        notificationRuleCooldownSeconds,
        memoryUsageDisplayMode,
        memoryUsageRefreshIntervalMs,
        memoryUsageWarningNearMaxPercent,
        memoryUsageWarningTooltipEnabled,
        memoryUsageWarningToastEnabled,
        memoryUsageWarningPushyEnabled,
        memoryUsageWarningSoundEnabled,
        notificationRules,
        serverTreeUnreadChannelColor,
        serverTreeHighlightChannelColor,
        preserveDockLayoutBetweenSessions,
        matrixUserListNameDisplayMode);
  }

  public UiSettings withImageEmbedsCollapsedByDefault(boolean collapsed) {
    return new UiSettings(
        theme,
        chatFontFamily,
        chatFontSize,
        autoConnectOnStart,
        trayEnabled,
        trayCloseToTray,
        trayMinimizeToTray,
        trayStartMinimized,
        trayNotifyHighlights,
        trayNotifyPrivateMessages,
        trayNotifyConnectionState,
        trayNotifyOnlyWhenUnfocused,
        trayNotifyOnlyWhenMinimizedOrHidden,
        trayNotifySuppressWhenTargetActive,
        trayLinuxDbusActionsEnabled,
        trayNotificationBackendMode,
        imageEmbedsEnabled,
        collapsed,
        imageEmbedsMaxWidthPx,
        imageEmbedsMaxHeightPx,
        imageEmbedsAnimateGifs,
        linkPreviewsEnabled,
        linkPreviewsCollapsedByDefault,
        presenceFoldsEnabled,
        ctcpRequestsInActiveTargetEnabled,
        typingIndicatorsEnabled,
        typingIndicatorsReceiveEnabled,
        typingIndicatorsTreeStyle,
        typingIndicatorsTreeEnabled,
        typingIndicatorsUsersListEnabled,
        typingIndicatorsTranscriptEnabled,
        typingIndicatorsSendSignalEnabled,
        timestampsEnabled,
        timestampFormat,
        timestampsIncludeChatMessages,
        timestampsIncludePresenceMessages,
        chatHistoryInitialLoadLines,
        chatHistoryPageSize,
        chatHistoryAutoLoadWheelDebounceMs,
        chatHistoryLoadOlderChunkSize,
        chatHistoryLoadOlderChunkDelayMs,
        chatHistoryLoadOlderChunkEdtBudgetMs,
        chatHistoryDeferRichTextDuringBatch,
        chatHistoryRemoteRequestTimeoutSeconds,
        chatHistoryRemoteZncPlaybackTimeoutSeconds,
        chatHistoryRemoteZncPlaybackWindowMinutes,
        commandHistoryMaxSize,
        chatTranscriptMaxLinesPerTarget,
        clientLineColorEnabled,
        clientLineColor,
        outgoingDeliveryIndicatorsEnabled,
        serverTreeNotificationBadgesEnabled,
        userhostDiscoveryEnabled,
        userhostMinIntervalSeconds,
        userhostMaxCommandsPerMinute,
        userhostNickCooldownMinutes,
        userhostMaxNicksPerCommand,
        userInfoEnrichmentEnabled,
        userInfoEnrichmentUserhostMinIntervalSeconds,
        userInfoEnrichmentUserhostMaxCommandsPerMinute,
        userInfoEnrichmentUserhostNickCooldownMinutes,
        userInfoEnrichmentUserhostMaxNicksPerCommand,
        userInfoEnrichmentWhoisFallbackEnabled,
        userInfoEnrichmentWhoisMinIntervalSeconds,
        userInfoEnrichmentWhoisNickCooldownMinutes,
        userInfoEnrichmentPeriodicRefreshEnabled,
        userInfoEnrichmentPeriodicRefreshIntervalSeconds,
        userInfoEnrichmentPeriodicRefreshNicksPerTick,
        monitorIsonFallbackPollIntervalSeconds,
        notificationRuleCooldownSeconds,
        memoryUsageDisplayMode,
        memoryUsageRefreshIntervalMs,
        memoryUsageWarningNearMaxPercent,
        memoryUsageWarningTooltipEnabled,
        memoryUsageWarningToastEnabled,
        memoryUsageWarningPushyEnabled,
        memoryUsageWarningSoundEnabled,
        notificationRules,
        serverTreeUnreadChannelColor,
        serverTreeHighlightChannelColor,
        preserveDockLayoutBetweenSessions,
        matrixUserListNameDisplayMode);
  }

  public UiSettings withImageEmbedsMaxWidthPx(int maxWidthPx) {
    return new UiSettings(
        theme,
        chatFontFamily,
        chatFontSize,
        autoConnectOnStart,
        trayEnabled,
        trayCloseToTray,
        trayMinimizeToTray,
        trayStartMinimized,
        trayNotifyHighlights,
        trayNotifyPrivateMessages,
        trayNotifyConnectionState,
        trayNotifyOnlyWhenUnfocused,
        trayNotifyOnlyWhenMinimizedOrHidden,
        trayNotifySuppressWhenTargetActive,
        trayLinuxDbusActionsEnabled,
        trayNotificationBackendMode,
        imageEmbedsEnabled,
        imageEmbedsCollapsedByDefault,
        Math.max(0, maxWidthPx),
        imageEmbedsMaxHeightPx,
        imageEmbedsAnimateGifs,
        linkPreviewsEnabled,
        linkPreviewsCollapsedByDefault,
        presenceFoldsEnabled,
        ctcpRequestsInActiveTargetEnabled,
        typingIndicatorsEnabled,
        typingIndicatorsReceiveEnabled,
        typingIndicatorsTreeStyle,
        typingIndicatorsTreeEnabled,
        typingIndicatorsUsersListEnabled,
        typingIndicatorsTranscriptEnabled,
        typingIndicatorsSendSignalEnabled,
        timestampsEnabled,
        timestampFormat,
        timestampsIncludeChatMessages,
        timestampsIncludePresenceMessages,
        chatHistoryInitialLoadLines,
        chatHistoryPageSize,
        chatHistoryAutoLoadWheelDebounceMs,
        chatHistoryLoadOlderChunkSize,
        chatHistoryLoadOlderChunkDelayMs,
        chatHistoryLoadOlderChunkEdtBudgetMs,
        chatHistoryDeferRichTextDuringBatch,
        chatHistoryRemoteRequestTimeoutSeconds,
        chatHistoryRemoteZncPlaybackTimeoutSeconds,
        chatHistoryRemoteZncPlaybackWindowMinutes,
        commandHistoryMaxSize,
        chatTranscriptMaxLinesPerTarget,
        clientLineColorEnabled,
        clientLineColor,
        outgoingDeliveryIndicatorsEnabled,
        serverTreeNotificationBadgesEnabled,
        userhostDiscoveryEnabled,
        userhostMinIntervalSeconds,
        userhostMaxCommandsPerMinute,
        userhostNickCooldownMinutes,
        userhostMaxNicksPerCommand,
        userInfoEnrichmentEnabled,
        userInfoEnrichmentUserhostMinIntervalSeconds,
        userInfoEnrichmentUserhostMaxCommandsPerMinute,
        userInfoEnrichmentUserhostNickCooldownMinutes,
        userInfoEnrichmentUserhostMaxNicksPerCommand,
        userInfoEnrichmentWhoisFallbackEnabled,
        userInfoEnrichmentWhoisMinIntervalSeconds,
        userInfoEnrichmentWhoisNickCooldownMinutes,
        userInfoEnrichmentPeriodicRefreshEnabled,
        userInfoEnrichmentPeriodicRefreshIntervalSeconds,
        userInfoEnrichmentPeriodicRefreshNicksPerTick,
        monitorIsonFallbackPollIntervalSeconds,
        notificationRuleCooldownSeconds,
        memoryUsageDisplayMode,
        memoryUsageRefreshIntervalMs,
        memoryUsageWarningNearMaxPercent,
        memoryUsageWarningTooltipEnabled,
        memoryUsageWarningToastEnabled,
        memoryUsageWarningPushyEnabled,
        memoryUsageWarningSoundEnabled,
        notificationRules,
        serverTreeUnreadChannelColor,
        serverTreeHighlightChannelColor,
        preserveDockLayoutBetweenSessions,
        matrixUserListNameDisplayMode);
  }

  public UiSettings withImageEmbedsMaxHeightPx(int maxHeightPx) {
    return new UiSettings(
        theme,
        chatFontFamily,
        chatFontSize,
        autoConnectOnStart,
        trayEnabled,
        trayCloseToTray,
        trayMinimizeToTray,
        trayStartMinimized,
        trayNotifyHighlights,
        trayNotifyPrivateMessages,
        trayNotifyConnectionState,
        trayNotifyOnlyWhenUnfocused,
        trayNotifyOnlyWhenMinimizedOrHidden,
        trayNotifySuppressWhenTargetActive,
        trayLinuxDbusActionsEnabled,
        trayNotificationBackendMode,
        imageEmbedsEnabled,
        imageEmbedsCollapsedByDefault,
        imageEmbedsMaxWidthPx,
        Math.max(0, maxHeightPx),
        imageEmbedsAnimateGifs,
        linkPreviewsEnabled,
        linkPreviewsCollapsedByDefault,
        presenceFoldsEnabled,
        ctcpRequestsInActiveTargetEnabled,
        typingIndicatorsEnabled,
        typingIndicatorsReceiveEnabled,
        typingIndicatorsTreeStyle,
        typingIndicatorsTreeEnabled,
        typingIndicatorsUsersListEnabled,
        typingIndicatorsTranscriptEnabled,
        typingIndicatorsSendSignalEnabled,
        timestampsEnabled,
        timestampFormat,
        timestampsIncludeChatMessages,
        timestampsIncludePresenceMessages,
        chatHistoryInitialLoadLines,
        chatHistoryPageSize,
        chatHistoryAutoLoadWheelDebounceMs,
        chatHistoryLoadOlderChunkSize,
        chatHistoryLoadOlderChunkDelayMs,
        chatHistoryLoadOlderChunkEdtBudgetMs,
        chatHistoryDeferRichTextDuringBatch,
        chatHistoryRemoteRequestTimeoutSeconds,
        chatHistoryRemoteZncPlaybackTimeoutSeconds,
        chatHistoryRemoteZncPlaybackWindowMinutes,
        commandHistoryMaxSize,
        chatTranscriptMaxLinesPerTarget,
        clientLineColorEnabled,
        clientLineColor,
        outgoingDeliveryIndicatorsEnabled,
        serverTreeNotificationBadgesEnabled,
        userhostDiscoveryEnabled,
        userhostMinIntervalSeconds,
        userhostMaxCommandsPerMinute,
        userhostNickCooldownMinutes,
        userhostMaxNicksPerCommand,
        userInfoEnrichmentEnabled,
        userInfoEnrichmentUserhostMinIntervalSeconds,
        userInfoEnrichmentUserhostMaxCommandsPerMinute,
        userInfoEnrichmentUserhostNickCooldownMinutes,
        userInfoEnrichmentUserhostMaxNicksPerCommand,
        userInfoEnrichmentWhoisFallbackEnabled,
        userInfoEnrichmentWhoisMinIntervalSeconds,
        userInfoEnrichmentWhoisNickCooldownMinutes,
        userInfoEnrichmentPeriodicRefreshEnabled,
        userInfoEnrichmentPeriodicRefreshIntervalSeconds,
        userInfoEnrichmentPeriodicRefreshNicksPerTick,
        monitorIsonFallbackPollIntervalSeconds,
        notificationRuleCooldownSeconds,
        memoryUsageDisplayMode,
        memoryUsageRefreshIntervalMs,
        memoryUsageWarningNearMaxPercent,
        memoryUsageWarningTooltipEnabled,
        memoryUsageWarningToastEnabled,
        memoryUsageWarningPushyEnabled,
        memoryUsageWarningSoundEnabled,
        notificationRules,
        serverTreeUnreadChannelColor,
        serverTreeHighlightChannelColor,
        preserveDockLayoutBetweenSessions,
        matrixUserListNameDisplayMode);
  }

  public UiSettings withLinkPreviewsEnabled(boolean enabled) {
    return new UiSettings(
        theme,
        chatFontFamily,
        chatFontSize,
        autoConnectOnStart,
        trayEnabled,
        trayCloseToTray,
        trayMinimizeToTray,
        trayStartMinimized,
        trayNotifyHighlights,
        trayNotifyPrivateMessages,
        trayNotifyConnectionState,
        trayNotifyOnlyWhenUnfocused,
        trayNotifyOnlyWhenMinimizedOrHidden,
        trayNotifySuppressWhenTargetActive,
        trayLinuxDbusActionsEnabled,
        trayNotificationBackendMode,
        imageEmbedsEnabled,
        imageEmbedsCollapsedByDefault,
        imageEmbedsMaxWidthPx,
        imageEmbedsMaxHeightPx,
        imageEmbedsAnimateGifs,
        enabled,
        linkPreviewsCollapsedByDefault,
        presenceFoldsEnabled,
        ctcpRequestsInActiveTargetEnabled,
        typingIndicatorsEnabled,
        typingIndicatorsReceiveEnabled,
        typingIndicatorsTreeStyle,
        typingIndicatorsTreeEnabled,
        typingIndicatorsUsersListEnabled,
        typingIndicatorsTranscriptEnabled,
        typingIndicatorsSendSignalEnabled,
        timestampsEnabled,
        timestampFormat,
        timestampsIncludeChatMessages,
        timestampsIncludePresenceMessages,
        chatHistoryInitialLoadLines,
        chatHistoryPageSize,
        chatHistoryAutoLoadWheelDebounceMs,
        chatHistoryLoadOlderChunkSize,
        chatHistoryLoadOlderChunkDelayMs,
        chatHistoryLoadOlderChunkEdtBudgetMs,
        chatHistoryDeferRichTextDuringBatch,
        chatHistoryRemoteRequestTimeoutSeconds,
        chatHistoryRemoteZncPlaybackTimeoutSeconds,
        chatHistoryRemoteZncPlaybackWindowMinutes,
        commandHistoryMaxSize,
        chatTranscriptMaxLinesPerTarget,
        clientLineColorEnabled,
        clientLineColor,
        outgoingDeliveryIndicatorsEnabled,
        serverTreeNotificationBadgesEnabled,
        userhostDiscoveryEnabled,
        userhostMinIntervalSeconds,
        userhostMaxCommandsPerMinute,
        userhostNickCooldownMinutes,
        userhostMaxNicksPerCommand,
        userInfoEnrichmentEnabled,
        userInfoEnrichmentUserhostMinIntervalSeconds,
        userInfoEnrichmentUserhostMaxCommandsPerMinute,
        userInfoEnrichmentUserhostNickCooldownMinutes,
        userInfoEnrichmentUserhostMaxNicksPerCommand,
        userInfoEnrichmentWhoisFallbackEnabled,
        userInfoEnrichmentWhoisMinIntervalSeconds,
        userInfoEnrichmentWhoisNickCooldownMinutes,
        userInfoEnrichmentPeriodicRefreshEnabled,
        userInfoEnrichmentPeriodicRefreshIntervalSeconds,
        userInfoEnrichmentPeriodicRefreshNicksPerTick,
        monitorIsonFallbackPollIntervalSeconds,
        notificationRuleCooldownSeconds,
        memoryUsageDisplayMode,
        memoryUsageRefreshIntervalMs,
        memoryUsageWarningNearMaxPercent,
        memoryUsageWarningTooltipEnabled,
        memoryUsageWarningToastEnabled,
        memoryUsageWarningPushyEnabled,
        memoryUsageWarningSoundEnabled,
        notificationRules,
        serverTreeUnreadChannelColor,
        serverTreeHighlightChannelColor,
        preserveDockLayoutBetweenSessions,
        matrixUserListNameDisplayMode);
  }

  public UiSettings withLinkPreviewsCollapsedByDefault(boolean collapsed) {
    return new UiSettings(
        theme,
        chatFontFamily,
        chatFontSize,
        autoConnectOnStart,
        trayEnabled,
        trayCloseToTray,
        trayMinimizeToTray,
        trayStartMinimized,
        trayNotifyHighlights,
        trayNotifyPrivateMessages,
        trayNotifyConnectionState,
        trayNotifyOnlyWhenUnfocused,
        trayNotifyOnlyWhenMinimizedOrHidden,
        trayNotifySuppressWhenTargetActive,
        trayLinuxDbusActionsEnabled,
        trayNotificationBackendMode,
        imageEmbedsEnabled,
        imageEmbedsCollapsedByDefault,
        imageEmbedsMaxWidthPx,
        imageEmbedsMaxHeightPx,
        imageEmbedsAnimateGifs,
        linkPreviewsEnabled,
        collapsed,
        presenceFoldsEnabled,
        ctcpRequestsInActiveTargetEnabled,
        typingIndicatorsEnabled,
        typingIndicatorsReceiveEnabled,
        typingIndicatorsTreeStyle,
        typingIndicatorsTreeEnabled,
        typingIndicatorsUsersListEnabled,
        typingIndicatorsTranscriptEnabled,
        typingIndicatorsSendSignalEnabled,
        timestampsEnabled,
        timestampFormat,
        timestampsIncludeChatMessages,
        timestampsIncludePresenceMessages,
        chatHistoryInitialLoadLines,
        chatHistoryPageSize,
        chatHistoryAutoLoadWheelDebounceMs,
        chatHistoryLoadOlderChunkSize,
        chatHistoryLoadOlderChunkDelayMs,
        chatHistoryLoadOlderChunkEdtBudgetMs,
        chatHistoryDeferRichTextDuringBatch,
        chatHistoryRemoteRequestTimeoutSeconds,
        chatHistoryRemoteZncPlaybackTimeoutSeconds,
        chatHistoryRemoteZncPlaybackWindowMinutes,
        commandHistoryMaxSize,
        chatTranscriptMaxLinesPerTarget,
        clientLineColorEnabled,
        clientLineColor,
        outgoingDeliveryIndicatorsEnabled,
        serverTreeNotificationBadgesEnabled,
        userhostDiscoveryEnabled,
        userhostMinIntervalSeconds,
        userhostMaxCommandsPerMinute,
        userhostNickCooldownMinutes,
        userhostMaxNicksPerCommand,
        userInfoEnrichmentEnabled,
        userInfoEnrichmentUserhostMinIntervalSeconds,
        userInfoEnrichmentUserhostMaxCommandsPerMinute,
        userInfoEnrichmentUserhostNickCooldownMinutes,
        userInfoEnrichmentUserhostMaxNicksPerCommand,
        userInfoEnrichmentWhoisFallbackEnabled,
        userInfoEnrichmentWhoisMinIntervalSeconds,
        userInfoEnrichmentWhoisNickCooldownMinutes,
        userInfoEnrichmentPeriodicRefreshEnabled,
        userInfoEnrichmentPeriodicRefreshIntervalSeconds,
        userInfoEnrichmentPeriodicRefreshNicksPerTick,
        monitorIsonFallbackPollIntervalSeconds,
        notificationRuleCooldownSeconds,
        memoryUsageDisplayMode,
        memoryUsageRefreshIntervalMs,
        memoryUsageWarningNearMaxPercent,
        memoryUsageWarningTooltipEnabled,
        memoryUsageWarningToastEnabled,
        memoryUsageWarningPushyEnabled,
        memoryUsageWarningSoundEnabled,
        notificationRules,
        serverTreeUnreadChannelColor,
        serverTreeHighlightChannelColor,
        preserveDockLayoutBetweenSessions,
        matrixUserListNameDisplayMode);
  }

  public UiSettings withPresenceFoldsEnabled(boolean enabled) {
    return new UiSettings(
        theme,
        chatFontFamily,
        chatFontSize,
        autoConnectOnStart,
        trayEnabled,
        trayCloseToTray,
        trayMinimizeToTray,
        trayStartMinimized,
        trayNotifyHighlights,
        trayNotifyPrivateMessages,
        trayNotifyConnectionState,
        trayNotifyOnlyWhenUnfocused,
        trayNotifyOnlyWhenMinimizedOrHidden,
        trayNotifySuppressWhenTargetActive,
        trayLinuxDbusActionsEnabled,
        trayNotificationBackendMode,
        imageEmbedsEnabled,
        imageEmbedsCollapsedByDefault,
        imageEmbedsMaxWidthPx,
        imageEmbedsMaxHeightPx,
        imageEmbedsAnimateGifs,
        linkPreviewsEnabled,
        linkPreviewsCollapsedByDefault,
        enabled,
        ctcpRequestsInActiveTargetEnabled,
        typingIndicatorsEnabled,
        typingIndicatorsReceiveEnabled,
        typingIndicatorsTreeStyle,
        typingIndicatorsTreeEnabled,
        typingIndicatorsUsersListEnabled,
        typingIndicatorsTranscriptEnabled,
        typingIndicatorsSendSignalEnabled,
        timestampsEnabled,
        timestampFormat,
        timestampsIncludeChatMessages,
        timestampsIncludePresenceMessages,
        chatHistoryInitialLoadLines,
        chatHistoryPageSize,
        chatHistoryAutoLoadWheelDebounceMs,
        chatHistoryLoadOlderChunkSize,
        chatHistoryLoadOlderChunkDelayMs,
        chatHistoryLoadOlderChunkEdtBudgetMs,
        chatHistoryDeferRichTextDuringBatch,
        chatHistoryRemoteRequestTimeoutSeconds,
        chatHistoryRemoteZncPlaybackTimeoutSeconds,
        chatHistoryRemoteZncPlaybackWindowMinutes,
        commandHistoryMaxSize,
        chatTranscriptMaxLinesPerTarget,
        clientLineColorEnabled,
        clientLineColor,
        outgoingDeliveryIndicatorsEnabled,
        serverTreeNotificationBadgesEnabled,
        userhostDiscoveryEnabled,
        userhostMinIntervalSeconds,
        userhostMaxCommandsPerMinute,
        userhostNickCooldownMinutes,
        userhostMaxNicksPerCommand,
        userInfoEnrichmentEnabled,
        userInfoEnrichmentUserhostMinIntervalSeconds,
        userInfoEnrichmentUserhostMaxCommandsPerMinute,
        userInfoEnrichmentUserhostNickCooldownMinutes,
        userInfoEnrichmentUserhostMaxNicksPerCommand,
        userInfoEnrichmentWhoisFallbackEnabled,
        userInfoEnrichmentWhoisMinIntervalSeconds,
        userInfoEnrichmentWhoisNickCooldownMinutes,
        userInfoEnrichmentPeriodicRefreshEnabled,
        userInfoEnrichmentPeriodicRefreshIntervalSeconds,
        userInfoEnrichmentPeriodicRefreshNicksPerTick,
        monitorIsonFallbackPollIntervalSeconds,
        notificationRuleCooldownSeconds,
        memoryUsageDisplayMode,
        memoryUsageRefreshIntervalMs,
        memoryUsageWarningNearMaxPercent,
        memoryUsageWarningTooltipEnabled,
        memoryUsageWarningToastEnabled,
        memoryUsageWarningPushyEnabled,
        memoryUsageWarningSoundEnabled,
        notificationRules,
        serverTreeUnreadChannelColor,
        serverTreeHighlightChannelColor,
        preserveDockLayoutBetweenSessions,
        matrixUserListNameDisplayMode);
  }

  public UiSettings withTypingIndicatorsEnabled(boolean enabled) {
    return new UiSettings(
        theme,
        chatFontFamily,
        chatFontSize,
        autoConnectOnStart,
        trayEnabled,
        trayCloseToTray,
        trayMinimizeToTray,
        trayStartMinimized,
        trayNotifyHighlights,
        trayNotifyPrivateMessages,
        trayNotifyConnectionState,
        trayNotifyOnlyWhenUnfocused,
        trayNotifyOnlyWhenMinimizedOrHidden,
        trayNotifySuppressWhenTargetActive,
        trayLinuxDbusActionsEnabled,
        trayNotificationBackendMode,
        imageEmbedsEnabled,
        imageEmbedsCollapsedByDefault,
        imageEmbedsMaxWidthPx,
        imageEmbedsMaxHeightPx,
        imageEmbedsAnimateGifs,
        linkPreviewsEnabled,
        linkPreviewsCollapsedByDefault,
        presenceFoldsEnabled,
        ctcpRequestsInActiveTargetEnabled,
        enabled,
        enabled,
        typingIndicatorsTreeStyle,
        typingIndicatorsTreeEnabled,
        typingIndicatorsUsersListEnabled,
        typingIndicatorsTranscriptEnabled,
        typingIndicatorsSendSignalEnabled,
        timestampsEnabled,
        timestampFormat,
        timestampsIncludeChatMessages,
        timestampsIncludePresenceMessages,
        chatHistoryInitialLoadLines,
        chatHistoryPageSize,
        chatHistoryAutoLoadWheelDebounceMs,
        chatHistoryLoadOlderChunkSize,
        chatHistoryLoadOlderChunkDelayMs,
        chatHistoryLoadOlderChunkEdtBudgetMs,
        chatHistoryDeferRichTextDuringBatch,
        chatHistoryRemoteRequestTimeoutSeconds,
        chatHistoryRemoteZncPlaybackTimeoutSeconds,
        chatHistoryRemoteZncPlaybackWindowMinutes,
        commandHistoryMaxSize,
        chatTranscriptMaxLinesPerTarget,
        clientLineColorEnabled,
        clientLineColor,
        outgoingDeliveryIndicatorsEnabled,
        serverTreeNotificationBadgesEnabled,
        userhostDiscoveryEnabled,
        userhostMinIntervalSeconds,
        userhostMaxCommandsPerMinute,
        userhostNickCooldownMinutes,
        userhostMaxNicksPerCommand,
        userInfoEnrichmentEnabled,
        userInfoEnrichmentUserhostMinIntervalSeconds,
        userInfoEnrichmentUserhostMaxCommandsPerMinute,
        userInfoEnrichmentUserhostNickCooldownMinutes,
        userInfoEnrichmentUserhostMaxNicksPerCommand,
        userInfoEnrichmentWhoisFallbackEnabled,
        userInfoEnrichmentWhoisMinIntervalSeconds,
        userInfoEnrichmentWhoisNickCooldownMinutes,
        userInfoEnrichmentPeriodicRefreshEnabled,
        userInfoEnrichmentPeriodicRefreshIntervalSeconds,
        userInfoEnrichmentPeriodicRefreshNicksPerTick,
        monitorIsonFallbackPollIntervalSeconds,
        notificationRuleCooldownSeconds,
        memoryUsageDisplayMode,
        memoryUsageRefreshIntervalMs,
        memoryUsageWarningNearMaxPercent,
        memoryUsageWarningTooltipEnabled,
        memoryUsageWarningToastEnabled,
        memoryUsageWarningPushyEnabled,
        memoryUsageWarningSoundEnabled,
        notificationRules,
        serverTreeUnreadChannelColor,
        serverTreeHighlightChannelColor,
        preserveDockLayoutBetweenSessions,
        matrixUserListNameDisplayMode);
  }

  public UiSettings withTypingIndicatorsReceiveEnabled(boolean enabled) {
    return new UiSettings(
        theme,
        chatFontFamily,
        chatFontSize,
        autoConnectOnStart,
        trayEnabled,
        trayCloseToTray,
        trayMinimizeToTray,
        trayStartMinimized,
        trayNotifyHighlights,
        trayNotifyPrivateMessages,
        trayNotifyConnectionState,
        trayNotifyOnlyWhenUnfocused,
        trayNotifyOnlyWhenMinimizedOrHidden,
        trayNotifySuppressWhenTargetActive,
        trayLinuxDbusActionsEnabled,
        trayNotificationBackendMode,
        imageEmbedsEnabled,
        imageEmbedsCollapsedByDefault,
        imageEmbedsMaxWidthPx,
        imageEmbedsMaxHeightPx,
        imageEmbedsAnimateGifs,
        linkPreviewsEnabled,
        linkPreviewsCollapsedByDefault,
        presenceFoldsEnabled,
        ctcpRequestsInActiveTargetEnabled,
        typingIndicatorsEnabled,
        enabled,
        typingIndicatorsTreeStyle,
        typingIndicatorsTreeEnabled,
        typingIndicatorsUsersListEnabled,
        typingIndicatorsTranscriptEnabled,
        typingIndicatorsSendSignalEnabled,
        timestampsEnabled,
        timestampFormat,
        timestampsIncludeChatMessages,
        timestampsIncludePresenceMessages,
        chatHistoryInitialLoadLines,
        chatHistoryPageSize,
        chatHistoryAutoLoadWheelDebounceMs,
        chatHistoryLoadOlderChunkSize,
        chatHistoryLoadOlderChunkDelayMs,
        chatHistoryLoadOlderChunkEdtBudgetMs,
        chatHistoryDeferRichTextDuringBatch,
        chatHistoryRemoteRequestTimeoutSeconds,
        chatHistoryRemoteZncPlaybackTimeoutSeconds,
        chatHistoryRemoteZncPlaybackWindowMinutes,
        commandHistoryMaxSize,
        chatTranscriptMaxLinesPerTarget,
        clientLineColorEnabled,
        clientLineColor,
        outgoingDeliveryIndicatorsEnabled,
        serverTreeNotificationBadgesEnabled,
        userhostDiscoveryEnabled,
        userhostMinIntervalSeconds,
        userhostMaxCommandsPerMinute,
        userhostNickCooldownMinutes,
        userhostMaxNicksPerCommand,
        userInfoEnrichmentEnabled,
        userInfoEnrichmentUserhostMinIntervalSeconds,
        userInfoEnrichmentUserhostMaxCommandsPerMinute,
        userInfoEnrichmentUserhostNickCooldownMinutes,
        userInfoEnrichmentUserhostMaxNicksPerCommand,
        userInfoEnrichmentWhoisFallbackEnabled,
        userInfoEnrichmentWhoisMinIntervalSeconds,
        userInfoEnrichmentWhoisNickCooldownMinutes,
        userInfoEnrichmentPeriodicRefreshEnabled,
        userInfoEnrichmentPeriodicRefreshIntervalSeconds,
        userInfoEnrichmentPeriodicRefreshNicksPerTick,
        monitorIsonFallbackPollIntervalSeconds,
        notificationRuleCooldownSeconds,
        memoryUsageDisplayMode,
        memoryUsageRefreshIntervalMs,
        memoryUsageWarningNearMaxPercent,
        memoryUsageWarningTooltipEnabled,
        memoryUsageWarningToastEnabled,
        memoryUsageWarningPushyEnabled,
        memoryUsageWarningSoundEnabled,
        notificationRules,
        serverTreeUnreadChannelColor,
        serverTreeHighlightChannelColor,
        preserveDockLayoutBetweenSessions,
        matrixUserListNameDisplayMode);
  }

  public UiSettings withTypingIndicatorsTreeEnabled(boolean enabled) {
    return new UiSettings(
        theme,
        chatFontFamily,
        chatFontSize,
        autoConnectOnStart,
        trayEnabled,
        trayCloseToTray,
        trayMinimizeToTray,
        trayStartMinimized,
        trayNotifyHighlights,
        trayNotifyPrivateMessages,
        trayNotifyConnectionState,
        trayNotifyOnlyWhenUnfocused,
        trayNotifyOnlyWhenMinimizedOrHidden,
        trayNotifySuppressWhenTargetActive,
        trayLinuxDbusActionsEnabled,
        trayNotificationBackendMode,
        imageEmbedsEnabled,
        imageEmbedsCollapsedByDefault,
        imageEmbedsMaxWidthPx,
        imageEmbedsMaxHeightPx,
        imageEmbedsAnimateGifs,
        linkPreviewsEnabled,
        linkPreviewsCollapsedByDefault,
        presenceFoldsEnabled,
        ctcpRequestsInActiveTargetEnabled,
        typingIndicatorsEnabled,
        typingIndicatorsReceiveEnabled,
        typingIndicatorsTreeStyle,
        enabled,
        typingIndicatorsUsersListEnabled,
        typingIndicatorsTranscriptEnabled,
        typingIndicatorsSendSignalEnabled,
        timestampsEnabled,
        timestampFormat,
        timestampsIncludeChatMessages,
        timestampsIncludePresenceMessages,
        chatHistoryInitialLoadLines,
        chatHistoryPageSize,
        chatHistoryAutoLoadWheelDebounceMs,
        chatHistoryLoadOlderChunkSize,
        chatHistoryLoadOlderChunkDelayMs,
        chatHistoryLoadOlderChunkEdtBudgetMs,
        chatHistoryDeferRichTextDuringBatch,
        chatHistoryRemoteRequestTimeoutSeconds,
        chatHistoryRemoteZncPlaybackTimeoutSeconds,
        chatHistoryRemoteZncPlaybackWindowMinutes,
        commandHistoryMaxSize,
        chatTranscriptMaxLinesPerTarget,
        clientLineColorEnabled,
        clientLineColor,
        outgoingDeliveryIndicatorsEnabled,
        serverTreeNotificationBadgesEnabled,
        userhostDiscoveryEnabled,
        userhostMinIntervalSeconds,
        userhostMaxCommandsPerMinute,
        userhostNickCooldownMinutes,
        userhostMaxNicksPerCommand,
        userInfoEnrichmentEnabled,
        userInfoEnrichmentUserhostMinIntervalSeconds,
        userInfoEnrichmentUserhostMaxCommandsPerMinute,
        userInfoEnrichmentUserhostNickCooldownMinutes,
        userInfoEnrichmentUserhostMaxNicksPerCommand,
        userInfoEnrichmentWhoisFallbackEnabled,
        userInfoEnrichmentWhoisMinIntervalSeconds,
        userInfoEnrichmentWhoisNickCooldownMinutes,
        userInfoEnrichmentPeriodicRefreshEnabled,
        userInfoEnrichmentPeriodicRefreshIntervalSeconds,
        userInfoEnrichmentPeriodicRefreshNicksPerTick,
        monitorIsonFallbackPollIntervalSeconds,
        notificationRuleCooldownSeconds,
        memoryUsageDisplayMode,
        memoryUsageRefreshIntervalMs,
        memoryUsageWarningNearMaxPercent,
        memoryUsageWarningTooltipEnabled,
        memoryUsageWarningToastEnabled,
        memoryUsageWarningPushyEnabled,
        memoryUsageWarningSoundEnabled,
        notificationRules,
        serverTreeUnreadChannelColor,
        serverTreeHighlightChannelColor,
        preserveDockLayoutBetweenSessions,
        matrixUserListNameDisplayMode);
  }

  public UiSettings withTypingIndicatorsUsersListEnabled(boolean enabled) {
    return new UiSettings(
        theme,
        chatFontFamily,
        chatFontSize,
        autoConnectOnStart,
        trayEnabled,
        trayCloseToTray,
        trayMinimizeToTray,
        trayStartMinimized,
        trayNotifyHighlights,
        trayNotifyPrivateMessages,
        trayNotifyConnectionState,
        trayNotifyOnlyWhenUnfocused,
        trayNotifyOnlyWhenMinimizedOrHidden,
        trayNotifySuppressWhenTargetActive,
        trayLinuxDbusActionsEnabled,
        trayNotificationBackendMode,
        imageEmbedsEnabled,
        imageEmbedsCollapsedByDefault,
        imageEmbedsMaxWidthPx,
        imageEmbedsMaxHeightPx,
        imageEmbedsAnimateGifs,
        linkPreviewsEnabled,
        linkPreviewsCollapsedByDefault,
        presenceFoldsEnabled,
        ctcpRequestsInActiveTargetEnabled,
        typingIndicatorsEnabled,
        typingIndicatorsReceiveEnabled,
        typingIndicatorsTreeStyle,
        typingIndicatorsTreeEnabled,
        enabled,
        typingIndicatorsTranscriptEnabled,
        typingIndicatorsSendSignalEnabled,
        timestampsEnabled,
        timestampFormat,
        timestampsIncludeChatMessages,
        timestampsIncludePresenceMessages,
        chatHistoryInitialLoadLines,
        chatHistoryPageSize,
        chatHistoryAutoLoadWheelDebounceMs,
        chatHistoryLoadOlderChunkSize,
        chatHistoryLoadOlderChunkDelayMs,
        chatHistoryLoadOlderChunkEdtBudgetMs,
        chatHistoryDeferRichTextDuringBatch,
        chatHistoryRemoteRequestTimeoutSeconds,
        chatHistoryRemoteZncPlaybackTimeoutSeconds,
        chatHistoryRemoteZncPlaybackWindowMinutes,
        commandHistoryMaxSize,
        chatTranscriptMaxLinesPerTarget,
        clientLineColorEnabled,
        clientLineColor,
        outgoingDeliveryIndicatorsEnabled,
        serverTreeNotificationBadgesEnabled,
        userhostDiscoveryEnabled,
        userhostMinIntervalSeconds,
        userhostMaxCommandsPerMinute,
        userhostNickCooldownMinutes,
        userhostMaxNicksPerCommand,
        userInfoEnrichmentEnabled,
        userInfoEnrichmentUserhostMinIntervalSeconds,
        userInfoEnrichmentUserhostMaxCommandsPerMinute,
        userInfoEnrichmentUserhostNickCooldownMinutes,
        userInfoEnrichmentUserhostMaxNicksPerCommand,
        userInfoEnrichmentWhoisFallbackEnabled,
        userInfoEnrichmentWhoisMinIntervalSeconds,
        userInfoEnrichmentWhoisNickCooldownMinutes,
        userInfoEnrichmentPeriodicRefreshEnabled,
        userInfoEnrichmentPeriodicRefreshIntervalSeconds,
        userInfoEnrichmentPeriodicRefreshNicksPerTick,
        monitorIsonFallbackPollIntervalSeconds,
        notificationRuleCooldownSeconds,
        memoryUsageDisplayMode,
        memoryUsageRefreshIntervalMs,
        memoryUsageWarningNearMaxPercent,
        memoryUsageWarningTooltipEnabled,
        memoryUsageWarningToastEnabled,
        memoryUsageWarningPushyEnabled,
        memoryUsageWarningSoundEnabled,
        notificationRules,
        serverTreeUnreadChannelColor,
        serverTreeHighlightChannelColor,
        preserveDockLayoutBetweenSessions,
        matrixUserListNameDisplayMode);
  }

  public UiSettings withTypingIndicatorsTranscriptEnabled(boolean enabled) {
    return new UiSettings(
        theme,
        chatFontFamily,
        chatFontSize,
        autoConnectOnStart,
        trayEnabled,
        trayCloseToTray,
        trayMinimizeToTray,
        trayStartMinimized,
        trayNotifyHighlights,
        trayNotifyPrivateMessages,
        trayNotifyConnectionState,
        trayNotifyOnlyWhenUnfocused,
        trayNotifyOnlyWhenMinimizedOrHidden,
        trayNotifySuppressWhenTargetActive,
        trayLinuxDbusActionsEnabled,
        trayNotificationBackendMode,
        imageEmbedsEnabled,
        imageEmbedsCollapsedByDefault,
        imageEmbedsMaxWidthPx,
        imageEmbedsMaxHeightPx,
        imageEmbedsAnimateGifs,
        linkPreviewsEnabled,
        linkPreviewsCollapsedByDefault,
        presenceFoldsEnabled,
        ctcpRequestsInActiveTargetEnabled,
        typingIndicatorsEnabled,
        typingIndicatorsReceiveEnabled,
        typingIndicatorsTreeStyle,
        typingIndicatorsTreeEnabled,
        typingIndicatorsUsersListEnabled,
        enabled,
        typingIndicatorsSendSignalEnabled,
        timestampsEnabled,
        timestampFormat,
        timestampsIncludeChatMessages,
        timestampsIncludePresenceMessages,
        chatHistoryInitialLoadLines,
        chatHistoryPageSize,
        chatHistoryAutoLoadWheelDebounceMs,
        chatHistoryLoadOlderChunkSize,
        chatHistoryLoadOlderChunkDelayMs,
        chatHistoryLoadOlderChunkEdtBudgetMs,
        chatHistoryDeferRichTextDuringBatch,
        chatHistoryRemoteRequestTimeoutSeconds,
        chatHistoryRemoteZncPlaybackTimeoutSeconds,
        chatHistoryRemoteZncPlaybackWindowMinutes,
        commandHistoryMaxSize,
        chatTranscriptMaxLinesPerTarget,
        clientLineColorEnabled,
        clientLineColor,
        outgoingDeliveryIndicatorsEnabled,
        serverTreeNotificationBadgesEnabled,
        userhostDiscoveryEnabled,
        userhostMinIntervalSeconds,
        userhostMaxCommandsPerMinute,
        userhostNickCooldownMinutes,
        userhostMaxNicksPerCommand,
        userInfoEnrichmentEnabled,
        userInfoEnrichmentUserhostMinIntervalSeconds,
        userInfoEnrichmentUserhostMaxCommandsPerMinute,
        userInfoEnrichmentUserhostNickCooldownMinutes,
        userInfoEnrichmentUserhostMaxNicksPerCommand,
        userInfoEnrichmentWhoisFallbackEnabled,
        userInfoEnrichmentWhoisMinIntervalSeconds,
        userInfoEnrichmentWhoisNickCooldownMinutes,
        userInfoEnrichmentPeriodicRefreshEnabled,
        userInfoEnrichmentPeriodicRefreshIntervalSeconds,
        userInfoEnrichmentPeriodicRefreshNicksPerTick,
        monitorIsonFallbackPollIntervalSeconds,
        notificationRuleCooldownSeconds,
        memoryUsageDisplayMode,
        memoryUsageRefreshIntervalMs,
        memoryUsageWarningNearMaxPercent,
        memoryUsageWarningTooltipEnabled,
        memoryUsageWarningToastEnabled,
        memoryUsageWarningPushyEnabled,
        memoryUsageWarningSoundEnabled,
        notificationRules,
        serverTreeUnreadChannelColor,
        serverTreeHighlightChannelColor,
        preserveDockLayoutBetweenSessions,
        matrixUserListNameDisplayMode);
  }

  public UiSettings withTypingIndicatorsSendSignalEnabled(boolean enabled) {
    return new UiSettings(
        theme,
        chatFontFamily,
        chatFontSize,
        autoConnectOnStart,
        trayEnabled,
        trayCloseToTray,
        trayMinimizeToTray,
        trayStartMinimized,
        trayNotifyHighlights,
        trayNotifyPrivateMessages,
        trayNotifyConnectionState,
        trayNotifyOnlyWhenUnfocused,
        trayNotifyOnlyWhenMinimizedOrHidden,
        trayNotifySuppressWhenTargetActive,
        trayLinuxDbusActionsEnabled,
        trayNotificationBackendMode,
        imageEmbedsEnabled,
        imageEmbedsCollapsedByDefault,
        imageEmbedsMaxWidthPx,
        imageEmbedsMaxHeightPx,
        imageEmbedsAnimateGifs,
        linkPreviewsEnabled,
        linkPreviewsCollapsedByDefault,
        presenceFoldsEnabled,
        ctcpRequestsInActiveTargetEnabled,
        typingIndicatorsEnabled,
        typingIndicatorsReceiveEnabled,
        typingIndicatorsTreeStyle,
        typingIndicatorsTreeEnabled,
        typingIndicatorsUsersListEnabled,
        typingIndicatorsTranscriptEnabled,
        enabled,
        timestampsEnabled,
        timestampFormat,
        timestampsIncludeChatMessages,
        timestampsIncludePresenceMessages,
        chatHistoryInitialLoadLines,
        chatHistoryPageSize,
        chatHistoryAutoLoadWheelDebounceMs,
        chatHistoryLoadOlderChunkSize,
        chatHistoryLoadOlderChunkDelayMs,
        chatHistoryLoadOlderChunkEdtBudgetMs,
        chatHistoryDeferRichTextDuringBatch,
        chatHistoryRemoteRequestTimeoutSeconds,
        chatHistoryRemoteZncPlaybackTimeoutSeconds,
        chatHistoryRemoteZncPlaybackWindowMinutes,
        commandHistoryMaxSize,
        chatTranscriptMaxLinesPerTarget,
        clientLineColorEnabled,
        clientLineColor,
        outgoingDeliveryIndicatorsEnabled,
        serverTreeNotificationBadgesEnabled,
        userhostDiscoveryEnabled,
        userhostMinIntervalSeconds,
        userhostMaxCommandsPerMinute,
        userhostNickCooldownMinutes,
        userhostMaxNicksPerCommand,
        userInfoEnrichmentEnabled,
        userInfoEnrichmentUserhostMinIntervalSeconds,
        userInfoEnrichmentUserhostMaxCommandsPerMinute,
        userInfoEnrichmentUserhostNickCooldownMinutes,
        userInfoEnrichmentUserhostMaxNicksPerCommand,
        userInfoEnrichmentWhoisFallbackEnabled,
        userInfoEnrichmentWhoisMinIntervalSeconds,
        userInfoEnrichmentWhoisNickCooldownMinutes,
        userInfoEnrichmentPeriodicRefreshEnabled,
        userInfoEnrichmentPeriodicRefreshIntervalSeconds,
        userInfoEnrichmentPeriodicRefreshNicksPerTick,
        monitorIsonFallbackPollIntervalSeconds,
        notificationRuleCooldownSeconds,
        memoryUsageDisplayMode,
        memoryUsageRefreshIntervalMs,
        memoryUsageWarningNearMaxPercent,
        memoryUsageWarningTooltipEnabled,
        memoryUsageWarningToastEnabled,
        memoryUsageWarningPushyEnabled,
        memoryUsageWarningSoundEnabled,
        notificationRules,
        serverTreeUnreadChannelColor,
        serverTreeHighlightChannelColor,
        preserveDockLayoutBetweenSessions,
        matrixUserListNameDisplayMode);
  }

  public UiSettings withTimestampsEnabled(boolean enabled) {
    return new UiSettings(
        theme,
        chatFontFamily,
        chatFontSize,
        autoConnectOnStart,
        trayEnabled,
        trayCloseToTray,
        trayMinimizeToTray,
        trayStartMinimized,
        trayNotifyHighlights,
        trayNotifyPrivateMessages,
        trayNotifyConnectionState,
        trayNotifyOnlyWhenUnfocused,
        trayNotifyOnlyWhenMinimizedOrHidden,
        trayNotifySuppressWhenTargetActive,
        trayLinuxDbusActionsEnabled,
        trayNotificationBackendMode,
        imageEmbedsEnabled,
        imageEmbedsCollapsedByDefault,
        imageEmbedsMaxWidthPx,
        imageEmbedsMaxHeightPx,
        imageEmbedsAnimateGifs,
        linkPreviewsEnabled,
        linkPreviewsCollapsedByDefault,
        presenceFoldsEnabled,
        ctcpRequestsInActiveTargetEnabled,
        typingIndicatorsEnabled,
        typingIndicatorsReceiveEnabled,
        typingIndicatorsTreeStyle,
        typingIndicatorsTreeEnabled,
        typingIndicatorsUsersListEnabled,
        typingIndicatorsTranscriptEnabled,
        typingIndicatorsSendSignalEnabled,
        enabled,
        timestampFormat,
        timestampsIncludeChatMessages,
        timestampsIncludePresenceMessages,
        chatHistoryInitialLoadLines,
        chatHistoryPageSize,
        chatHistoryAutoLoadWheelDebounceMs,
        chatHistoryLoadOlderChunkSize,
        chatHistoryLoadOlderChunkDelayMs,
        chatHistoryLoadOlderChunkEdtBudgetMs,
        chatHistoryDeferRichTextDuringBatch,
        chatHistoryRemoteRequestTimeoutSeconds,
        chatHistoryRemoteZncPlaybackTimeoutSeconds,
        chatHistoryRemoteZncPlaybackWindowMinutes,
        commandHistoryMaxSize,
        chatTranscriptMaxLinesPerTarget,
        clientLineColorEnabled,
        clientLineColor,
        outgoingDeliveryIndicatorsEnabled,
        serverTreeNotificationBadgesEnabled,
        userhostDiscoveryEnabled,
        userhostMinIntervalSeconds,
        userhostMaxCommandsPerMinute,
        userhostNickCooldownMinutes,
        userhostMaxNicksPerCommand,
        userInfoEnrichmentEnabled,
        userInfoEnrichmentUserhostMinIntervalSeconds,
        userInfoEnrichmentUserhostMaxCommandsPerMinute,
        userInfoEnrichmentUserhostNickCooldownMinutes,
        userInfoEnrichmentUserhostMaxNicksPerCommand,
        userInfoEnrichmentWhoisFallbackEnabled,
        userInfoEnrichmentWhoisMinIntervalSeconds,
        userInfoEnrichmentWhoisNickCooldownMinutes,
        userInfoEnrichmentPeriodicRefreshEnabled,
        userInfoEnrichmentPeriodicRefreshIntervalSeconds,
        userInfoEnrichmentPeriodicRefreshNicksPerTick,
        monitorIsonFallbackPollIntervalSeconds,
        notificationRuleCooldownSeconds,
        memoryUsageDisplayMode,
        memoryUsageRefreshIntervalMs,
        memoryUsageWarningNearMaxPercent,
        memoryUsageWarningTooltipEnabled,
        memoryUsageWarningToastEnabled,
        memoryUsageWarningPushyEnabled,
        memoryUsageWarningSoundEnabled,
        notificationRules,
        serverTreeUnreadChannelColor,
        serverTreeHighlightChannelColor,
        preserveDockLayoutBetweenSessions,
        matrixUserListNameDisplayMode);
  }

  public UiSettings withTimestampFormat(String format) {
    return new UiSettings(
        theme,
        chatFontFamily,
        chatFontSize,
        autoConnectOnStart,
        trayEnabled,
        trayCloseToTray,
        trayMinimizeToTray,
        trayStartMinimized,
        trayNotifyHighlights,
        trayNotifyPrivateMessages,
        trayNotifyConnectionState,
        trayNotifyOnlyWhenUnfocused,
        trayNotifyOnlyWhenMinimizedOrHidden,
        trayNotifySuppressWhenTargetActive,
        trayLinuxDbusActionsEnabled,
        trayNotificationBackendMode,
        imageEmbedsEnabled,
        imageEmbedsCollapsedByDefault,
        imageEmbedsMaxWidthPx,
        imageEmbedsMaxHeightPx,
        imageEmbedsAnimateGifs,
        linkPreviewsEnabled,
        linkPreviewsCollapsedByDefault,
        presenceFoldsEnabled,
        ctcpRequestsInActiveTargetEnabled,
        typingIndicatorsEnabled,
        typingIndicatorsReceiveEnabled,
        typingIndicatorsTreeStyle,
        typingIndicatorsTreeEnabled,
        typingIndicatorsUsersListEnabled,
        typingIndicatorsTranscriptEnabled,
        typingIndicatorsSendSignalEnabled,
        timestampsEnabled,
        format,
        timestampsIncludeChatMessages,
        timestampsIncludePresenceMessages,
        chatHistoryInitialLoadLines,
        chatHistoryPageSize,
        chatHistoryAutoLoadWheelDebounceMs,
        chatHistoryLoadOlderChunkSize,
        chatHistoryLoadOlderChunkDelayMs,
        chatHistoryLoadOlderChunkEdtBudgetMs,
        chatHistoryDeferRichTextDuringBatch,
        chatHistoryRemoteRequestTimeoutSeconds,
        chatHistoryRemoteZncPlaybackTimeoutSeconds,
        chatHistoryRemoteZncPlaybackWindowMinutes,
        commandHistoryMaxSize,
        chatTranscriptMaxLinesPerTarget,
        clientLineColorEnabled,
        clientLineColor,
        outgoingDeliveryIndicatorsEnabled,
        serverTreeNotificationBadgesEnabled,
        userhostDiscoveryEnabled,
        userhostMinIntervalSeconds,
        userhostMaxCommandsPerMinute,
        userhostNickCooldownMinutes,
        userhostMaxNicksPerCommand,
        userInfoEnrichmentEnabled,
        userInfoEnrichmentUserhostMinIntervalSeconds,
        userInfoEnrichmentUserhostMaxCommandsPerMinute,
        userInfoEnrichmentUserhostNickCooldownMinutes,
        userInfoEnrichmentUserhostMaxNicksPerCommand,
        userInfoEnrichmentWhoisFallbackEnabled,
        userInfoEnrichmentWhoisMinIntervalSeconds,
        userInfoEnrichmentWhoisNickCooldownMinutes,
        userInfoEnrichmentPeriodicRefreshEnabled,
        userInfoEnrichmentPeriodicRefreshIntervalSeconds,
        userInfoEnrichmentPeriodicRefreshNicksPerTick,
        monitorIsonFallbackPollIntervalSeconds,
        notificationRuleCooldownSeconds,
        memoryUsageDisplayMode,
        memoryUsageRefreshIntervalMs,
        memoryUsageWarningNearMaxPercent,
        memoryUsageWarningTooltipEnabled,
        memoryUsageWarningToastEnabled,
        memoryUsageWarningPushyEnabled,
        memoryUsageWarningSoundEnabled,
        notificationRules,
        serverTreeUnreadChannelColor,
        serverTreeHighlightChannelColor,
        preserveDockLayoutBetweenSessions,
        matrixUserListNameDisplayMode);
  }

  public UiSettings withTimestampsIncludeChatMessages(boolean enabled) {
    return new UiSettings(
        theme,
        chatFontFamily,
        chatFontSize,
        autoConnectOnStart,
        trayEnabled,
        trayCloseToTray,
        trayMinimizeToTray,
        trayStartMinimized,
        trayNotifyHighlights,
        trayNotifyPrivateMessages,
        trayNotifyConnectionState,
        trayNotifyOnlyWhenUnfocused,
        trayNotifyOnlyWhenMinimizedOrHidden,
        trayNotifySuppressWhenTargetActive,
        trayLinuxDbusActionsEnabled,
        trayNotificationBackendMode,
        imageEmbedsEnabled,
        imageEmbedsCollapsedByDefault,
        imageEmbedsMaxWidthPx,
        imageEmbedsMaxHeightPx,
        imageEmbedsAnimateGifs,
        linkPreviewsEnabled,
        linkPreviewsCollapsedByDefault,
        presenceFoldsEnabled,
        ctcpRequestsInActiveTargetEnabled,
        typingIndicatorsEnabled,
        typingIndicatorsReceiveEnabled,
        typingIndicatorsTreeStyle,
        typingIndicatorsTreeEnabled,
        typingIndicatorsUsersListEnabled,
        typingIndicatorsTranscriptEnabled,
        typingIndicatorsSendSignalEnabled,
        timestampsEnabled,
        timestampFormat,
        enabled,
        timestampsIncludePresenceMessages,
        chatHistoryInitialLoadLines,
        chatHistoryPageSize,
        chatHistoryAutoLoadWheelDebounceMs,
        chatHistoryLoadOlderChunkSize,
        chatHistoryLoadOlderChunkDelayMs,
        chatHistoryLoadOlderChunkEdtBudgetMs,
        chatHistoryDeferRichTextDuringBatch,
        chatHistoryRemoteRequestTimeoutSeconds,
        chatHistoryRemoteZncPlaybackTimeoutSeconds,
        chatHistoryRemoteZncPlaybackWindowMinutes,
        commandHistoryMaxSize,
        chatTranscriptMaxLinesPerTarget,
        clientLineColorEnabled,
        clientLineColor,
        outgoingDeliveryIndicatorsEnabled,
        serverTreeNotificationBadgesEnabled,
        userhostDiscoveryEnabled,
        userhostMinIntervalSeconds,
        userhostMaxCommandsPerMinute,
        userhostNickCooldownMinutes,
        userhostMaxNicksPerCommand,
        userInfoEnrichmentEnabled,
        userInfoEnrichmentUserhostMinIntervalSeconds,
        userInfoEnrichmentUserhostMaxCommandsPerMinute,
        userInfoEnrichmentUserhostNickCooldownMinutes,
        userInfoEnrichmentUserhostMaxNicksPerCommand,
        userInfoEnrichmentWhoisFallbackEnabled,
        userInfoEnrichmentWhoisMinIntervalSeconds,
        userInfoEnrichmentWhoisNickCooldownMinutes,
        userInfoEnrichmentPeriodicRefreshEnabled,
        userInfoEnrichmentPeriodicRefreshIntervalSeconds,
        userInfoEnrichmentPeriodicRefreshNicksPerTick,
        monitorIsonFallbackPollIntervalSeconds,
        notificationRuleCooldownSeconds,
        memoryUsageDisplayMode,
        memoryUsageRefreshIntervalMs,
        memoryUsageWarningNearMaxPercent,
        memoryUsageWarningTooltipEnabled,
        memoryUsageWarningToastEnabled,
        memoryUsageWarningPushyEnabled,
        memoryUsageWarningSoundEnabled,
        notificationRules,
        serverTreeUnreadChannelColor,
        serverTreeHighlightChannelColor,
        preserveDockLayoutBetweenSessions,
        matrixUserListNameDisplayMode);
  }

  public UiSettings withTimestampsIncludePresenceMessages(boolean enabled) {
    return new UiSettings(
        theme,
        chatFontFamily,
        chatFontSize,
        autoConnectOnStart,
        trayEnabled,
        trayCloseToTray,
        trayMinimizeToTray,
        trayStartMinimized,
        trayNotifyHighlights,
        trayNotifyPrivateMessages,
        trayNotifyConnectionState,
        trayNotifyOnlyWhenUnfocused,
        trayNotifyOnlyWhenMinimizedOrHidden,
        trayNotifySuppressWhenTargetActive,
        trayLinuxDbusActionsEnabled,
        trayNotificationBackendMode,
        imageEmbedsEnabled,
        imageEmbedsCollapsedByDefault,
        imageEmbedsMaxWidthPx,
        imageEmbedsMaxHeightPx,
        imageEmbedsAnimateGifs,
        linkPreviewsEnabled,
        linkPreviewsCollapsedByDefault,
        presenceFoldsEnabled,
        ctcpRequestsInActiveTargetEnabled,
        typingIndicatorsEnabled,
        typingIndicatorsReceiveEnabled,
        typingIndicatorsTreeStyle,
        typingIndicatorsTreeEnabled,
        typingIndicatorsUsersListEnabled,
        typingIndicatorsTranscriptEnabled,
        typingIndicatorsSendSignalEnabled,
        timestampsEnabled,
        timestampFormat,
        timestampsIncludeChatMessages,
        enabled,
        chatHistoryInitialLoadLines,
        chatHistoryPageSize,
        chatHistoryAutoLoadWheelDebounceMs,
        chatHistoryLoadOlderChunkSize,
        chatHistoryLoadOlderChunkDelayMs,
        chatHistoryLoadOlderChunkEdtBudgetMs,
        chatHistoryDeferRichTextDuringBatch,
        chatHistoryRemoteRequestTimeoutSeconds,
        chatHistoryRemoteZncPlaybackTimeoutSeconds,
        chatHistoryRemoteZncPlaybackWindowMinutes,
        commandHistoryMaxSize,
        chatTranscriptMaxLinesPerTarget,
        clientLineColorEnabled,
        clientLineColor,
        outgoingDeliveryIndicatorsEnabled,
        serverTreeNotificationBadgesEnabled,
        userhostDiscoveryEnabled,
        userhostMinIntervalSeconds,
        userhostMaxCommandsPerMinute,
        userhostNickCooldownMinutes,
        userhostMaxNicksPerCommand,
        userInfoEnrichmentEnabled,
        userInfoEnrichmentUserhostMinIntervalSeconds,
        userInfoEnrichmentUserhostMaxCommandsPerMinute,
        userInfoEnrichmentUserhostNickCooldownMinutes,
        userInfoEnrichmentUserhostMaxNicksPerCommand,
        userInfoEnrichmentWhoisFallbackEnabled,
        userInfoEnrichmentWhoisMinIntervalSeconds,
        userInfoEnrichmentWhoisNickCooldownMinutes,
        userInfoEnrichmentPeriodicRefreshEnabled,
        userInfoEnrichmentPeriodicRefreshIntervalSeconds,
        userInfoEnrichmentPeriodicRefreshNicksPerTick,
        monitorIsonFallbackPollIntervalSeconds,
        notificationRuleCooldownSeconds,
        memoryUsageDisplayMode,
        memoryUsageRefreshIntervalMs,
        memoryUsageWarningNearMaxPercent,
        memoryUsageWarningTooltipEnabled,
        memoryUsageWarningToastEnabled,
        memoryUsageWarningPushyEnabled,
        memoryUsageWarningSoundEnabled,
        notificationRules,
        serverTreeUnreadChannelColor,
        serverTreeHighlightChannelColor,
        preserveDockLayoutBetweenSessions,
        matrixUserListNameDisplayMode);
  }

  @Deprecated
  public UiSettings withChatMessageTimestampsEnabled(boolean enabled) {
    return withTimestampsIncludeChatMessages(enabled);
  }

  public UiSettings withMemoryUsageDisplayMode(MemoryUsageDisplayMode mode) {
    return new UiSettings(
        theme,
        chatFontFamily,
        chatFontSize,
        autoConnectOnStart,
        trayEnabled,
        trayCloseToTray,
        trayMinimizeToTray,
        trayStartMinimized,
        trayNotifyHighlights,
        trayNotifyPrivateMessages,
        trayNotifyConnectionState,
        trayNotifyOnlyWhenUnfocused,
        trayNotifyOnlyWhenMinimizedOrHidden,
        trayNotifySuppressWhenTargetActive,
        trayLinuxDbusActionsEnabled,
        trayNotificationBackendMode,
        imageEmbedsEnabled,
        imageEmbedsCollapsedByDefault,
        imageEmbedsMaxWidthPx,
        imageEmbedsMaxHeightPx,
        imageEmbedsAnimateGifs,
        linkPreviewsEnabled,
        linkPreviewsCollapsedByDefault,
        presenceFoldsEnabled,
        ctcpRequestsInActiveTargetEnabled,
        typingIndicatorsEnabled,
        typingIndicatorsReceiveEnabled,
        typingIndicatorsTreeStyle,
        typingIndicatorsTreeEnabled,
        typingIndicatorsUsersListEnabled,
        typingIndicatorsTranscriptEnabled,
        typingIndicatorsSendSignalEnabled,
        timestampsEnabled,
        timestampFormat,
        timestampsIncludeChatMessages,
        timestampsIncludePresenceMessages,
        chatHistoryInitialLoadLines,
        chatHistoryPageSize,
        chatHistoryAutoLoadWheelDebounceMs,
        chatHistoryLoadOlderChunkSize,
        chatHistoryLoadOlderChunkDelayMs,
        chatHistoryLoadOlderChunkEdtBudgetMs,
        chatHistoryDeferRichTextDuringBatch,
        chatHistoryRemoteRequestTimeoutSeconds,
        chatHistoryRemoteZncPlaybackTimeoutSeconds,
        chatHistoryRemoteZncPlaybackWindowMinutes,
        commandHistoryMaxSize,
        chatTranscriptMaxLinesPerTarget,
        clientLineColorEnabled,
        clientLineColor,
        outgoingDeliveryIndicatorsEnabled,
        serverTreeNotificationBadgesEnabled,
        userhostDiscoveryEnabled,
        userhostMinIntervalSeconds,
        userhostMaxCommandsPerMinute,
        userhostNickCooldownMinutes,
        userhostMaxNicksPerCommand,
        userInfoEnrichmentEnabled,
        userInfoEnrichmentUserhostMinIntervalSeconds,
        userInfoEnrichmentUserhostMaxCommandsPerMinute,
        userInfoEnrichmentUserhostNickCooldownMinutes,
        userInfoEnrichmentUserhostMaxNicksPerCommand,
        userInfoEnrichmentWhoisFallbackEnabled,
        userInfoEnrichmentWhoisMinIntervalSeconds,
        userInfoEnrichmentWhoisNickCooldownMinutes,
        userInfoEnrichmentPeriodicRefreshEnabled,
        userInfoEnrichmentPeriodicRefreshIntervalSeconds,
        userInfoEnrichmentPeriodicRefreshNicksPerTick,
        monitorIsonFallbackPollIntervalSeconds,
        notificationRuleCooldownSeconds,
        mode,
        memoryUsageRefreshIntervalMs,
        memoryUsageWarningNearMaxPercent,
        memoryUsageWarningTooltipEnabled,
        memoryUsageWarningToastEnabled,
        memoryUsageWarningPushyEnabled,
        memoryUsageWarningSoundEnabled,
        notificationRules,
        serverTreeUnreadChannelColor,
        serverTreeHighlightChannelColor,
        preserveDockLayoutBetweenSessions,
        matrixUserListNameDisplayMode);
  }

  public UiSettings withMemoryUsageRefreshIntervalMs(int refreshIntervalMs) {
    return new UiSettings(
        theme,
        chatFontFamily,
        chatFontSize,
        autoConnectOnStart,
        trayEnabled,
        trayCloseToTray,
        trayMinimizeToTray,
        trayStartMinimized,
        trayNotifyHighlights,
        trayNotifyPrivateMessages,
        trayNotifyConnectionState,
        trayNotifyOnlyWhenUnfocused,
        trayNotifyOnlyWhenMinimizedOrHidden,
        trayNotifySuppressWhenTargetActive,
        trayLinuxDbusActionsEnabled,
        trayNotificationBackendMode,
        imageEmbedsEnabled,
        imageEmbedsCollapsedByDefault,
        imageEmbedsMaxWidthPx,
        imageEmbedsMaxHeightPx,
        imageEmbedsAnimateGifs,
        linkPreviewsEnabled,
        linkPreviewsCollapsedByDefault,
        presenceFoldsEnabled,
        ctcpRequestsInActiveTargetEnabled,
        typingIndicatorsEnabled,
        typingIndicatorsReceiveEnabled,
        typingIndicatorsTreeStyle,
        typingIndicatorsTreeEnabled,
        typingIndicatorsUsersListEnabled,
        typingIndicatorsTranscriptEnabled,
        typingIndicatorsSendSignalEnabled,
        timestampsEnabled,
        timestampFormat,
        timestampsIncludeChatMessages,
        timestampsIncludePresenceMessages,
        chatHistoryInitialLoadLines,
        chatHistoryPageSize,
        chatHistoryAutoLoadWheelDebounceMs,
        chatHistoryLoadOlderChunkSize,
        chatHistoryLoadOlderChunkDelayMs,
        chatHistoryLoadOlderChunkEdtBudgetMs,
        chatHistoryDeferRichTextDuringBatch,
        chatHistoryRemoteRequestTimeoutSeconds,
        chatHistoryRemoteZncPlaybackTimeoutSeconds,
        chatHistoryRemoteZncPlaybackWindowMinutes,
        commandHistoryMaxSize,
        chatTranscriptMaxLinesPerTarget,
        clientLineColorEnabled,
        clientLineColor,
        outgoingDeliveryIndicatorsEnabled,
        serverTreeNotificationBadgesEnabled,
        userhostDiscoveryEnabled,
        userhostMinIntervalSeconds,
        userhostMaxCommandsPerMinute,
        userhostNickCooldownMinutes,
        userhostMaxNicksPerCommand,
        userInfoEnrichmentEnabled,
        userInfoEnrichmentUserhostMinIntervalSeconds,
        userInfoEnrichmentUserhostMaxCommandsPerMinute,
        userInfoEnrichmentUserhostNickCooldownMinutes,
        userInfoEnrichmentUserhostMaxNicksPerCommand,
        userInfoEnrichmentWhoisFallbackEnabled,
        userInfoEnrichmentWhoisMinIntervalSeconds,
        userInfoEnrichmentWhoisNickCooldownMinutes,
        userInfoEnrichmentPeriodicRefreshEnabled,
        userInfoEnrichmentPeriodicRefreshIntervalSeconds,
        userInfoEnrichmentPeriodicRefreshNicksPerTick,
        monitorIsonFallbackPollIntervalSeconds,
        notificationRuleCooldownSeconds,
        memoryUsageDisplayMode,
        refreshIntervalMs,
        memoryUsageWarningNearMaxPercent,
        memoryUsageWarningTooltipEnabled,
        memoryUsageWarningToastEnabled,
        memoryUsageWarningPushyEnabled,
        memoryUsageWarningSoundEnabled,
        notificationRules,
        serverTreeUnreadChannelColor,
        serverTreeHighlightChannelColor,
        preserveDockLayoutBetweenSessions,
        matrixUserListNameDisplayMode);
  }

  public UiSettings withAutoConnectOnStart(boolean enabled) {
    return new UiSettings(
        theme,
        chatFontFamily,
        chatFontSize,
        enabled,
        trayEnabled,
        trayCloseToTray,
        trayMinimizeToTray,
        trayStartMinimized,
        trayNotifyHighlights,
        trayNotifyPrivateMessages,
        trayNotifyConnectionState,
        trayNotifyOnlyWhenUnfocused,
        trayNotifyOnlyWhenMinimizedOrHidden,
        trayNotifySuppressWhenTargetActive,
        trayLinuxDbusActionsEnabled,
        trayNotificationBackendMode,
        imageEmbedsEnabled,
        imageEmbedsCollapsedByDefault,
        imageEmbedsMaxWidthPx,
        imageEmbedsMaxHeightPx,
        imageEmbedsAnimateGifs,
        linkPreviewsEnabled,
        linkPreviewsCollapsedByDefault,
        presenceFoldsEnabled,
        ctcpRequestsInActiveTargetEnabled,
        typingIndicatorsEnabled,
        typingIndicatorsReceiveEnabled,
        typingIndicatorsTreeStyle,
        typingIndicatorsTreeEnabled,
        typingIndicatorsUsersListEnabled,
        typingIndicatorsTranscriptEnabled,
        typingIndicatorsSendSignalEnabled,
        timestampsEnabled,
        timestampFormat,
        timestampsIncludeChatMessages,
        timestampsIncludePresenceMessages,
        chatHistoryInitialLoadLines,
        chatHistoryPageSize,
        chatHistoryAutoLoadWheelDebounceMs,
        chatHistoryLoadOlderChunkSize,
        chatHistoryLoadOlderChunkDelayMs,
        chatHistoryLoadOlderChunkEdtBudgetMs,
        chatHistoryDeferRichTextDuringBatch,
        chatHistoryRemoteRequestTimeoutSeconds,
        chatHistoryRemoteZncPlaybackTimeoutSeconds,
        chatHistoryRemoteZncPlaybackWindowMinutes,
        commandHistoryMaxSize,
        chatTranscriptMaxLinesPerTarget,
        clientLineColorEnabled,
        clientLineColor,
        outgoingDeliveryIndicatorsEnabled,
        serverTreeNotificationBadgesEnabled,
        userhostDiscoveryEnabled,
        userhostMinIntervalSeconds,
        userhostMaxCommandsPerMinute,
        userhostNickCooldownMinutes,
        userhostMaxNicksPerCommand,
        userInfoEnrichmentEnabled,
        userInfoEnrichmentUserhostMinIntervalSeconds,
        userInfoEnrichmentUserhostMaxCommandsPerMinute,
        userInfoEnrichmentUserhostNickCooldownMinutes,
        userInfoEnrichmentUserhostMaxNicksPerCommand,
        userInfoEnrichmentWhoisFallbackEnabled,
        userInfoEnrichmentWhoisMinIntervalSeconds,
        userInfoEnrichmentWhoisNickCooldownMinutes,
        userInfoEnrichmentPeriodicRefreshEnabled,
        userInfoEnrichmentPeriodicRefreshIntervalSeconds,
        userInfoEnrichmentPeriodicRefreshNicksPerTick,
        monitorIsonFallbackPollIntervalSeconds,
        notificationRuleCooldownSeconds,
        memoryUsageDisplayMode,
        memoryUsageRefreshIntervalMs,
        memoryUsageWarningNearMaxPercent,
        memoryUsageWarningTooltipEnabled,
        memoryUsageWarningToastEnabled,
        memoryUsageWarningPushyEnabled,
        memoryUsageWarningSoundEnabled,
        notificationRules,
        serverTreeUnreadChannelColor,
        serverTreeHighlightChannelColor,
        preserveDockLayoutBetweenSessions,
        matrixUserListNameDisplayMode);
  }
}
